[package]
name = "vulkan-testing-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
pretty_env_logger = "0.5.0"
vulkanalia = "0.23.0"
winit = "0.30.1"
